### ISSUE TITLE
Compatibility issue with OptiFine It doesn't render emojis at all

### ISSUE THREAD

**Issue by SepSol** [Team-Fruit/Emojicord#1] opened 2019-10-25 21:57 UTC
![2019-10-26_01 05 57](https://user-images.githubusercontent.com/47871887/67606673-fdface80-f78e-11e9-870b-8e88efbef6f3.png)

Minecraft 1.14.4
Forge 28.1.61
EmojiCord 1.0.1.13

**Comment by KisaragiEffective** [comment] 2019-10-26 03:43
Could you list all mods? It seems other mods are also applied.

**Comment by SepSol** [comment] 2019-10-26 07:48
**These are all of my mods (Minecraft 1.14.4 - Forge 28.1.61):**

1. Valtiel's Girl Armor 2.9.2.1
2. AI Improvements 0.3.0
3. AmbientSounds 3.0.14
4. AstikorCarts 1.0.0.1
5. AutoMessageDisplayer 0.0.1.3
6. Better Advancements 0.1.0.90
7. Better Animals 5.2.1
8. Better Title Screen 1.7
9. Biome Info 1.2.4
10. Block Meter 1.1.3
11. Bottle Your XP 1.0
12. Camera 1.4.8
13. Campfire Torches 1.0.3
14. CarryOn 1.12.4
15. CC Tweaked 1.85.0
16. Cherished Worlds 2.0
17. Chunk Claim 2.7.0
18. Coloured Chat 1.4.1
19. Comforts 2.0-beta3
20. Console HUD 1.4.3
21. Controlling 5.0.4
22. Crafting Station 2.0.7
23. Craft Presence 1.5.6
24. Craft Tweaker 5.0.0
25. Create 0.1.1a
26. CustomSkinLoader 14.11
27. Default Options 10.2.6
28. Ding 1.1.0
29. Double Doors 1.1
30. Enchanting Commands 1.0
31. EmojiCord 1.0.1.13
32. Enchantment Descriptions 1.3.3
33. Equipment Tooltips 1.3.2+10
34. Extra Boats 1.1.2
35. Eyes In The Darkness 0.2.0
36. Just Fashion 2.1.0.2
37. Fast Workbench 2.1.4
38. Featured Servers 1.1.3
39. Filters 1.1.1
40. FreeLook 1.3.1
41. Give 1.0.1
42. GoProne 1.0.3
43. GUI Clock 1.3
44. GUI Compass 1.0
45. Simple Harvest 1.2.10-23
46. Hidden Levers
47. HWYLA 1.10.6-B67
48. I Like Wood 1.1.2.3
49. Item Scroller 0.15.0-dev.20191023.012451
50. JEI 6.0.0.18
51. Just Mob Heads 2.2
52. Just Player Heads 1.0
53. Just Enough Resources (JER) 0.10.0.63
54. KleeSlabs 7.4.7
55. MaliLib 0.10.0-dev.19+alpha.1
56. MineMenu 1.8.2
57. MoreCrashInfo 1.0.3
58. Morpheus 4.2.43
59. Named Areas 3.7
60. No Auto-Jump 1.1
61. Paintings++ 6.0.1.1
62. Pass-through Signs 2.3.1
63. Public GUI Announcement 1.1.0.0
64. Placebo 2.3.1
65. Realistic Utilities 3.2
66. Screenshot To Clipboard 1.0.2
67. ShoulderSurfing 1.21
68. Simple Farming 1.2.1
69. Sit 1.1.3
70. Smoke 1.0.2
71. Smooth Scrolling Everywhere 1.1
72. SubLib 2.0.1.0
73. Swing Through Grass 1.3.2
74. Tabs4Survival 1.0.0
75. Third-Person Elytra 1.2
76. TrashSlot 10.4.7
77. TreeChippin 1.2.0
78. WorldEdit 7.0.1
79. WorldHandler 2.6.5
80. OptiFine HD U F4 pre11

**Comment by sjcl** [comment] 2019-10-26 07:51
This is too much :/
Which mod is likely to be the cause?

**Comment by SepSol** [comment] 2019-10-26 09:18
Maybe something like ColouredChat is causing the problem, but honestly i don't know. I will try to test and update you!

**Comment by yahho** [comment] 2019-10-26 09:29
Suspicious mod(s): **OptiFine**
But I don't come up with way to fix this problem except putting out OptiFine from your mods folder at now.

**Comment by SepSol** [comment] 2019-10-26 10:45
Yup, it was **OptiFine**. Do you think there will be a fix in near future?

**Comment by SepSol** [comment] 2019-10-26 23:50
**Update:**
I tried the latest Forge (28.1.70) and OptiFine (HD U F4) and the issue still persists.

**Comment by fuzzyweapon** [comment] 2019-11-14 04:25
Also having troubles with the same versions of Forge, Optifine, and latest Emojicord.

We rely on optifine optimizations for players on our server.  Would really love a fix for this.

**Comment by Kamesuta** [comment] 2020-06-05 17:11
Fixed in Emojicord v1.1.1

**Closed by Kamesuta** 2020-06-05 17:11 UTC
Labels: bug, compatibility
